/*
 * REST API
 * This is a sample definition of the Oracle WMS Cloud REST API.  The views expressed here are my own and do not necessarily reflect the views of Oracle.
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.ApiException;
import java.math.BigDecimal;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ReportApi
 */
@Ignore
public class ReportApiTest {

    private final ReportApi api = new ReportApi();

    
    /**
     * ReportCustomInventorySummary_GET
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void reportCustomInventorySummaryGETTest() throws ApiException {
        String itemCode = null;
        BigDecimal companyId = null;
        String companyIdCode = null;
        BigDecimal facilityId = null;
        String facilityIdCode = null;
        Boolean writeHeaderLineFlg = null;
        Object response = api.reportCustomInventorySummaryGET(itemCode, companyId, companyIdCode, facilityId, facilityIdCode, writeHeaderLineFlg);

        // TODO: test validations
    }
    
}
