# coding: utf-8

"""
    REST API

    This is a sample definition of the Oracle WMS Cloud REST API.  The views expressed here are my own and do not necessarily reflect the views of Oracle.  # noqa: E501

    OpenAPI spec version: 1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.entitylocation_api import EntitylocationApi  # noqa: E501
from swagger_client.rest import ApiException


class TestEntitylocationApi(unittest.TestCase):
    """EntitylocationApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.entitylocation_api.EntitylocationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_entity_location_by_id_get(self):
        """Test case for entity_location_by_id_get

        EntityLocationById_GET  # noqa: E501
        """
        pass

    def test_entity_location_by_id_patch(self):
        """Test case for entity_location_by_id_patch

        EntityLocationById_PATCH  # noqa: E501
        """
        pass

    def test_entity_location_describe_get(self):
        """Test case for entity_location_describe_get

        EntityLocationDescribe_GET  # noqa: E501
        """
        pass

    def test_entity_location_get(self):
        """Test case for entity_location_get

        EntityLocation_GET  # noqa: E501
        """
        pass

    def test_entity_location_update_active_inventory_by_id_post(self):
        """Test case for entity_location_update_active_inventory_by_id_post

        EntityLocationUpdateActiveInventoryById_POST  # noqa: E501
        """
        pass

    def test_entity_location_update_active_inventory_post(self):
        """Test case for entity_location_update_active_inventory_post

        EntityLocationUpdateActiveInventory_POST  # noqa: E501
        """
        pass

    def test_entity_location_year_first_available_get(self):
        """Test case for entity_location_year_first_available_get

        EntityLocationYearFirstAvailable_GET  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
